version: '3'
services:
  mokapi:
    image: mokapi/mokapi:latest
    ports:
      - "80:80"
      - "3051:3051"
    volumes:
      - ./mokapi:/etc/mokapi
    command: ["--config", "/etc/mokapi/mokapi.yaml"]
