version: '3'
services:
  mokapi:
    image: mokapi/mokapi:latest
    ports:
      - "8080:8080"
      - "3051:3051"
    volumes:
      - ./mokapi:/etc/mokapi
    command: ["--providers-file-filename=/etc/mokapi/openapi.yaml"]
